services:
  LSP.api:
    image: lsp.api
    build:
      context: .
      dockerfile: LSP.API/Dockerfile
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      - SecurityBlockControl=true
