version: '3.4'

services:
  lsp_api:
    image: lsp_api
    container_name: lsp_api
    build:
      context: .
      dockerfile: LSP.API/Dockerfile
    ports:
      - "5020:5020"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5020
      - SecurityBlockControl=true
      - ConnectionStrings__LSPDbContextConnection=Server=lsp_db,1433;Database=lsp;Uid=sa;Password=lspteam1708?;MultiSubnetFailover=True;TrustServerCertificate=True;
    depends_on:
      - lsp_db
    networks:
      - dev

  lsp_db:
    image: mcr.microsoft.com/mssql/server:2022-latest #mcr.microsoft.com/azure-sql-edge
    container_name: lsp_db
    environment:
      SA_PASSWORD: lspteam1708?
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
      MSSQL_COLLATION: Turkish_CS_AS
      TZ: Europe/Istanbul
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - lsp_data:/var/opt/mssql/data
    networks:
      - dev

volumes:
  lsp_data:
    name: lsp_data
    external: true

networks:
  dev:
    driver: bridge